variable "metal_metro" {
  type        = string
  description = "Equinix Metal Metro"
}

variable "metal_project_id" {
  type        = string
  description = "Equinix Metal Project ID"
}

variable "deploy_demo" {
  type        = bool
  description = "Deploys a simple demo using a global IP as ingress and a hello-kubernetes pods"
  default     = false
}

variable "cluster_name" {
  type        = string
  description = "Cluster name"
  default     = "Cluster"
}

variable "plan_control_plane" {
  type        = string
  description = "Control plane type/size"
  default     = "c3.small.x86"
}

variable "plan_node" {
  type        = string
  description = "Node type/size"
  default     = "c3.small.x86"
}

variable "node_count" {
  type        = number
  description = "Number of nodes"
  default     = "0"
}

variable "ha" {
  type        = bool
  description = "HA (aka 3 control plane nodes)"
  default     = false
}

variable "os" {
  type        = string
  description = "Operating system"
  default     = "debian_11"
}

variable "control_plane_hostnames" {
  type        = string
  description = "Control plane hostname prefix"
  default     = "cp"
}

variable "node_hostnames" {
  type        = string
  description = "Node hostname prefix"
  default     = "node"
}

variable "custom_token" {
  type        = string
  description = "Token used for nodes to join the cluster (autogenerated otherwise)"
  default     = null
}

variable "ip_pool_count" {
  type        = number
  description = "Number of public IPv4 per metro to be used as LoadBalancers with MetalLB (it needs to be power of 2 between 0 and 256 as required by Equinix Metal)"
  default     = 0
  validation {
    condition     = contains([0, 1, 2, 4, 8, 16, 32, 64, 128, 256], var.ip_pool_count)
    error_message = "The value must be a power of 2 between 0 and 256."
  }
}

variable "global_ip_cidr" {
  type        = string
  description = "Global Anycast IP that will be mapped on all metros via BGP"
  default     = null
}

variable "kube_version" {
  type        = string
  description = "K3s/RKE2 version to be installed. Empty for latest K3s"
  default     = ""
}

variable "metallb_version" {
  type        = string
  description = "MetalLB version to be installed. Empty for latest"
  default     = ""
}

variable "rancher_version" {
  type        = string
  description = "Rancher version to be installed (vX.Y.Z). Empty for latest"
  default     = ""
}

variable "rancher_flavor" {
  type        = string
  description = "Rancher flavor to be installed (prime, latest, stable or alpha). Empty to not install it"
  default     = ""
}

variable "custom_rancher_password" {
  type        = string
  description = "Rancher initial password (autogenerated if not provided)"
  default     = null
}
