variable "metal_metro" {
  type        = string
  description = "Equinix Metal Metro"
}

variable "metal_project_id" {
  type        = string
  description = "Equinix Metal Project ID"
}

variable "deploy_demo" {
  type        = bool
  description = "Deploys a simple demo using a global IP as ingress and a hello-kubernetes pods"
  default     = false
}

variable "cluster_name" {
  type        = string
  description = "Cluster name"
  default     = "K3s cluster"
}

variable "plan_control_plane" {
  type        = string
  description = "K3s control plane type/size"
  default     = "c3.small.x86"
}

variable "plan_node" {
  type        = string
  description = "K3s node type/size"
  default     = "c3.small.x86"
}

variable "node_count" {
  type        = number
  description = "Number of K3s nodes"
  default     = "0"
}

variable "k3s_ha" {
  type        = bool
  description = "K3s HA (aka 3 control plane nodes)"
  default     = false
}

variable "os" {
  type        = string
  description = "Operating system"
  default     = "debian_11"
}

variable "control_plane_hostnames" {
  type        = string
  description = "Control plane hostname prefix"
  default     = "cp"
}

variable "node_hostnames" {
  type        = string
  description = "Node hostname prefix"
  default     = "node"
}

variable "custom_k3s_token" {
  type        = string
  description = "K3s token used for nodes to join the cluster (autogenerated otherwise)"
  default     = null
}

variable "ip_pool_count" {
  type        = number
  description = "Number of public IPv4 per metro to be used as LoadBalancers with MetalLB"
  default     = 0
}

variable "global_ip_cidr" {
  type        = string
  description = "Global Anycast IP that will be mapped on all metros via BGP"
  default     = null
}

variable "k3s_version" {
  type        = string
  description = "K3s version to be installed. Empty for latest"
  default     = ""
}

variable "metallb_version" {
  type        = string
  description = "MetalLB version to be installed. Empty for latest"
  default     = ""
}
